version: '3'

services:
  postgres:
    container_name: warehousedb
    image: postgres:13.1-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: warehousedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - warehouse-postgres-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
volumes:
  warehouse-postgres-data:
    driver: local
