spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5435}/warehousedb
    password: ${POSTGRES_PASS:postgres}
    username: ${POSTGRES_USER:postgres}

