name: Build and test image
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
      - name: Build and test with Gradle Wrapper
        run: ./gradlew clean build